### ISSUE TITLE
I want to add `\left( ` and `\right)` as a pair (latex), how do I make sure it activates over the `()` pair

### ISSUE THREAD

**Issue by IndianBoy42** [windwp/nvim-autopairs#121]
i added 
```
  R("\\left(", " \\right)", "tex"),
```

And it spuriously works, sometimes it adds in `\right)` but sometimes it will add just `)`. Generally the way it happens is that it will work once/a few times then go back to `()` forever after that. Is there anyway to set a priority or workaround this that doesnt involve not putting a `(` at the end of the lhs of the pair

**Comment by windwp** [comment]
the order is arranged by string length than the rule `\\left(` will have a high order then rule `(` 

I think you have a similar issue with that issue on multiple char with filetype.
https://github.com/windwp/nvim-autopairs/issues/107
I don't know how to reproduce.
because you say it work a few times and after that, it stops work so i guess maybe the rule is disappearing on that filetype so you can't trigger that rule. :(

maybe when that happens you can try to run `:e` on command and check again

**Comment by IndianBoy42** [comment]
Running `:e` does seem to 'reset' something and I can use the pair once more before it stops working again. It does seem similar to #107 

Running that command you gave me doesn't show anything except the built in pairs, whether I just opened the file or not, although some of my custom pairs do work, they do not show up in MPairs

**Comment by windwp** [comment]
can you compare the result of that command when your rule is working?

**Comment by IndianBoy42** [comment]
The result of the command is the same whenever I run it. Even if I run it right after doing the add_pairs call

**Comment by windwp** [comment]
but it should have \left when you can use that rule?

**Comment by windwp** [comment]
hm you should run it on command line

https://user-images.githubusercontent.com/7578110/131984104-99ee13d3-7b39-4474-ba93-52e44008e0c5.mp4

**Comment by IndianBoy42** [comment]
Hmm I don't know what I changed but know the autopairs never work and they don't show up in MPairs.state.rules either

(btw here is my config: https://github.com/IndianBoy42/LunarVim/blob/master/lua/lv-autopairs/init.lua is everything there reasonable?)

**Comment by windwp** [comment]
sorry i try your autopairs config and it working to me.

if you have a step  or video to how to reproduce the issue then i will take a look again
