### ISSUE TITLE
Add rules for filetypes or treesitter context ?

### ISSUE THREAD

**Issue by kiuKisas** [windwp/nvim-autopairs#200]
**Is your feature request related to a problem? Please describe.**
In `rescript`, type parameter are written as `'a`. It only occurs in type definition. Single quote is also use for char, as expected: `'a'` , but we need it wayy less than type parameter.

**Describe the solution you'd like**
So I was thinking that it could be nice to have a proper per filetypes config, as some languages can have different behavior, disable or add rules can be handy.

**Describe alternatives you've considered**
Further more, It could be even better if we can add rules according to treesitter context (e.g: disable the second singlequote in type definition).

**Additional context**
That's all.  any though ? Looks like I can manage that with custom rules, is it correct ?

**Comment by windwp** [comment]
https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/rules/basic.lua#L40
this is how i define a double quote for specify vim filetype.

you can define a rule with condition base on treesitter but it will not  correct  on some case 
because we use it on insert mode when your code is not finish and treesitter can't specify a node name correct.
```lua
    Rule('<', '>', 'rust')
        :with_pair(ts_conds.is_ts_node({
            'type_identifier',
            'let_declaration',
            'parameters',
        }))
        :with_cr(cond.none()),
```

**Comment by kiuKisas** [comment]
I see, thank's for your explanation. You did a great job regarding personnalisation of your plugin ! 💪
