### ISSUE TITLE
Don't remove indentation on empty line

### ISSUE THREAD

**Issue by emi2k01** [windwp/nvim-autopairs#272]
**Is your feature request related to a problem? Please describe.**
After using `nvim-autopairs` cursor is `|` in insert mode
```
let x = {
    |
};
```
Leave insert mode, now cursor is moved to the start of the line
```
let x = {
|
};
```

**Describe the solution you'd like**
Allow an option to not remove the indentation on empty lines

**Describe alternatives you've considered**
Before using this plugin, I had a mapping like `imap <CR> <CR>x<BS>` so that the indentation wouldn't be deleted. The problem now is that `nvim-autopairs` hijacks the mapping so I can't use the old mapping anymore.

**Comment by windwp** [comment]
It use `O` key to add new line.
https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/rule.lua#L113
you can get the rule and modify the key with 
```
require('nvim-autopairs').get_rule('{'):replace_map_cr(function ()
   return "your custom key"
end)
```

**Comment by emi2k01** [comment]
Thank you!

```lua
require("nvim-autopairs").get_rule("{"):replace_map_cr(function()
    return "<C-g>u<CR><C-c>Ox<BS>"
end)
```

**Comment by TheBabu** [comment]
I don't mean to necrobump, but I was wondering how I could have it such that any additional enters will still have the same indentation. Meaning:
```
let x = {
    |
      ...
    |
    |
};
```

Will have the same indentation line indefinitely no matter how many enters I put. @emi2k01 I tried using the 
`map("i", "<CR>", "<CR>x<BS>", { silent = true })` in your config, but the issue is that it doesn't "expand" like I would expect.

Here is a recording of what I mean:
https://asciinema.org/a/655640

Thanks for any help in advance!
