### ISSUE TITLE
Fly Mode like in jiangmiao/auto-pairs

### ISSUE THREAD

**Issue by marlun** [windwp/nvim-autopairs#307]
**Is your feature request related to a problem? Please describe.**
When you're deep inside nested pairs it's nice to be able to jump to the end of the line in a fast way without having to leave insert mode or input all the ending characters.

**Describe the solution you'd like**
There's a good explanation at https://github.com/jiangmiao/auto-pairs if you search for "Fly Mode".

**Describe alternatives you've considered**
You'll have to leave insert mode and use normal mode commands which is OK but Fly Mode is an interesting solution. Not sure if it would make the code more complex and if it's not worth it but I still wanted to bring it up.

**Additional context**
Adding the description as a screenshot here: 
<img width="860" alt="image" src="https://user-images.githubusercontent.com/19663/209654978-eb20cadf-7f2f-418f-a9ba-5a42ed5820f4.png">

**Comment by windwp** [comment]
if you want to jump out  of a pair you can check this 
https://github.com/windwp/nvim-autopairs/issues/167
 My plugin processes a pair of values that are located on the current line. I don't want to scan multiple lines in order to locate the values, as this would involve scanning 4, 5, or even 20 lines, which would be inefficient.

**Comment by marlun** [comment]
No worries, I'll close this issue since you're clear about not wanting to do it. I'll take a look at #167 or get my brain to use CTRL-O more 😄
