### ISSUE TITLE
Do not autocomplete function with parentheses inside import statements

### ISSUE THREAD

**Issue by eldar** [windwp/nvim-autopairs#466]
**Is your feature request related to a problem? Please describe.**
There is a single issue with this excellent plugin that is slightly frustrating, namely inserting parentheses when auto-completing function imports - in my case in Python, but others have reported the same for [JavaScript](https://github.com/windwp/nvim-autopairs/issues/219). It is hard for me to imagine a case where the current behavior makes sense, and even if it does it would serve only a small fraction of use cases. I chose to report it as a feature request, however it is more severe than that, because inserting parentheses in the import statement results in the *incorrect code*.

**Describe the solution you'd like**
The default behavior is simply not to add parentheses when importing functions, because they cannot be called in that context.

**Comment by mageowl** [comment]
Can confirm for Rust as well.

**Comment by palvarezcordoba** [comment]
I hope this gets fixed (as i consider this a bug not an enhancement).
In the mean time, i configured the integration between cmp and autopairs. 
If you’re using cmp too, you can check my config: https://github.com/palvarezcordoba/neovim-config/blob/f416c3b9b91a812dc8eeab231a52df00afed1187/lua/plugins/autopairs.lua

If you use another completion engine i guess you would do something similar. 

Now however that currently works only on imports that span only 1 line, and it could disable adding parenthesis sometimes because i use a bad crafted regex

**Comment by me-nkr** [comment]
+1
